-- IconsManifest.lua — GENERATED by tools/build-icon-manifest.sh.
-- DO NOT HAND-EDIT: re-running the script overwrites this file.
--
-- Maps spellID/itemID to a filename in IconsHD/. The art itself is NOT in
-- this repo (IconsHD/ is gitignored) — this file is only the index that lets
-- GB know what exists, since WoW cannot enumerate files. An empty table is
-- the correct shipped state: anyone without the art gets Blizzard's icons.
--
-- Explicit /gb icon overrides take priority over anything listed here.

local GB = _G.GloomsBars
if not GB then return end

GB.ICON_MANIFEST = {
}
