#!/usr/bin/env bash
#
# build-icon-manifest.sh — regenerate IconsManifest.lua from the IconsHD/ folder.
#
# WoW exposes no filesystem API: an addon cannot list a folder or test whether a
# file exists. So something outside the game has to tell GB what art you made.
# That is this script. Drop icons into IconsHD/, run this, /reload.
#
# ★ The ID is the LAST underscore/hyphen-separated segment. Everything before it
# is yours — sort and group however you like:
#
#   IconsHD/hunter_mm_aimedshot_19434.tga    -> spell 19434
#   IconsHD/hunter_all_exhilaration_109304.tga -> spell 109304
#   IconsHD/264735.tga                       -> spell 264735 (bare ID still fine)
#   IconsHD/misc_healthstone_i5512.tga       -> item 5512 ('i' prefix)
#
# The final segment must be ALL digits, so "hunter_mm_volley.tga" (ID forgotten)
# is rejected rather than guessed at. Anything unparseable is REPORTED, never
# silently skipped.
#
# IconsHD/ is gitignored — your art never enters the repo. IconsManifest.lua IS
# tracked, and holds nothing but ID->filename pairs.

set -euo pipefail
cd "$(dirname "$0")/.."

DIR="IconsHD"
OUT="IconsManifest.lua"

mkdir -p "$DIR"

entries=""
count=0
skipped=0

# Sorted, NUL-safe, and tolerant of an empty folder.
while IFS= read -r -d '' f; do
  base="$(basename "$f")"
  case "$base" in
    .*) continue ;;                     # dotfiles (.DS_Store, probes)
  esac
  ext="$(printf '%s' "${base##*.}" | tr '[:upper:]' '[:lower:]')"
  if [ "$ext" != "tga" ] && [ "$ext" != "png" ]; then
    printf '  SKIP (not .tga/.png): %s\n' "$base" >&2
    skipped=$((skipped + 1))
    continue
  fi

  # Strip the extension, then take everything after the LAST '_' or '-'. With no
  # separator at all this is the whole name, so a bare "264735.tga" still works.
  stem="${base%.*}"
  tail="${stem##*[-_]}"

  key=""
  if [[ "$tail" =~ ^([0-9]+)$ ]]; then
    key="spell:${BASH_REMATCH[1]}"
  elif [[ "$tail" =~ ^[Ii]([0-9]+)$ ]]; then
    key="item:${BASH_REMATCH[1]}"
  else
    printf '  SKIP (last segment is not an ID): %s\n' "$base" >&2
    skipped=$((skipped + 1))
    continue
  fi

  # Lua string escape: backslashes and quotes. Filenames should not contain
  # either, but generating code from filenames without escaping is how you get a
  # syntax error that looks like a game bug.
  esc="$(printf '%s' "$base" | sed 's/\\/\\\\/g; s/"/\\"/g')"
  entries="${entries}  [\"${key}\"] = \"${esc}\",
"
  count=$((count + 1))
done < <(find "$DIR" -maxdepth 1 -type f -print0 2>/dev/null | sort -z)

{
  echo "-- IconsManifest.lua — GENERATED by tools/build-icon-manifest.sh."
  echo "-- DO NOT HAND-EDIT: re-running the script overwrites this file."
  echo "--"
  echo "-- Maps spellID/itemID to a filename in IconsHD/. The art itself is NOT in"
  echo "-- this repo (IconsHD/ is gitignored) — this file is only the index that lets"
  echo "-- GB know what exists, since WoW cannot enumerate files. An empty table is"
  echo "-- the correct shipped state: anyone without the art gets Blizzard's icons."
  echo "--"
  echo "-- Explicit /gb icon overrides take priority over anything listed here."
  echo ""
  echo "local GB = _G.GloomsBars"
  echo "if not GB then return end"
  echo ""
  echo "GB.ICON_MANIFEST = {"
  printf '%s' "$entries"
  echo "}"
} > "$OUT"

printf 'wrote %s — %d icon(s), %d skipped\n' "$OUT" "$count" "$skipped"
